apiVersion: apps/v1
kind: Deployment
metadata:
  name: loveshoppingclient-deployment
  labels:
    app: loveshoppingclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loveshoppingclient
  template:
    metadata:
      labels:
        app: loveshoppingclient
    spec:
      containers:
        - name: loveshoppingclient
          image: loveshoppingacr.azurecr.io/loveshoppingclient:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: loveshoppingapi-configmap
                    key: loveshoppingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: loveshoppingclient-service
spec:
  type: NodePort
  selector:
    app: loveshoppingclient
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30000